"""
Document Generation Module - PDF & PPTX
"""
import streamlit as st
import time

def generate_pdf(structured_content, output_path="transcript.pdf"):
    """Generate a PDF from structured content"""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
        from reportlab.lib import colors
        
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2c3e50'),
            alignment=TA_CENTER,
            spaceAfter=30
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#34495e'),
            spaceBefore=20,
            spaceAfter=10
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
            leading=14
        )
        
        key_point_style = ParagraphStyle(
            'KeyPoint',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#8e44ad'),
            leftIndent=20,
            bulletIndent=10,
            spaceAfter=4
        )
        
        story = []
        
        story.append(Paragraph(structured_content.get('title', 'Video Transcript'), title_style))
        story.append(Spacer(1, 12))
        
        if structured_content.get('summary'):
            story.append(Paragraph('<b>Summary</b>', heading_style))
            story.append(Paragraph(structured_content['summary'], body_style))
            story.append(Spacer(1, 12))
        
        if structured_content.get('key_points'):
            story.append(Paragraph('<b>Key Points</b>', heading_style))
            for point in structured_content['key_points'][:10]:
                story.append(Paragraph(f'• {point}', key_point_style))
            story.append(Spacer(1, 12))
        
        for section in structured_content.get('sections', []):
            story.append(Paragraph(f'<b>{section["title"]}</b>', heading_style))
            for point in section['points']:
                story.append(Paragraph(point, body_style))
            story.append(Spacer(1, 6))
        
        doc.build(story)
        return output_path
        
    except Exception as e:
        st.error(f"PDF generation failed: {str(e)}")
        return None

def generate_pptx(structured_content, output_path="transcript.pptx"):
    """Generate a PPTX presentation from structured content"""
    try:
        from pptx import Presentation
        from pptx.util import Pt
        
        prs = Presentation()
        
        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = structured_content.get('title', 'Video Transcript')
        if prs.slide_layouts[0].placeholders:
            subtitle = title_slide.placeholders[1]
            subtitle.text = f"Generated by Video Frame Extractor Pro\n{time.strftime('%B %d, %Y')}"
        
        # Summary slide
        if structured_content.get('summary'):
            summary_slide = prs.slides.add_slide(prs.slide_layouts[1])
            summary_slide.shapes.title.text = "Summary"
            content = summary_slide.placeholders[1]
            text_frame = content.text_frame
            text_frame.text = structured_content['summary']
        
        # Key Points slide
        if structured_content.get('key_points'):
            key_slide = prs.slides.add_slide(prs.slide_layouts[1])
            key_slide.shapes.title.text = "Key Points"
            content = key_slide.placeholders[1]
            text_frame = content.text_frame
            text_frame.text = ""
            for point in structured_content['key_points'][:8]:
                p = text_frame.add_paragraph()
                p.text = point
                p.level = 0
                p.font.size = Pt(18)
                p.space_after = Pt(6)
        
        # Content slides
        for section in structured_content.get('sections', []):
            if not section['points']:
                continue
                
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = section['title']
            content = slide.placeholders[1]
            text_frame = content.text_frame
            text_frame.text = ""
            
            points_to_add = section['points'][:5]
            for point in points_to_add:
                p = text_frame.add_paragraph()
                p.text = point
                p.level = 0
                p.font.size = Pt(16)
                p.space_after = Pt(4)
        
        prs.save(output_path)
        return output_path
        
    except Exception as e:
        st.error(f"PPTX generation failed: {str(e)}")
        return None